function interfata1(R,L,C,tip, alegere, tipr, valr, tipc)
 close;
figure('Name','  Filtre   RLC',...
        'Numbertitle','off',...
        'Units','normalized',...
        'Position',[0.1 0.1 0.8 0.8],...
        'Color','w',...
        'Tag','interfata_c');
uibuttongroup('Visible','on',...
              'BackgroundColor','w',...
              'ForegroundColor','black',...
              'FontSize',15,...
              'FontWeight','b',...
              'TitlePosition','centertop',...
              'Title','Date de intrare',...
              'Position',[0.065 0.52 0.2 0.45]);
%-------------------------------------
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.085,0.88,0.1,0.03],...
          'BackgroundColor',[0.75,0.75,0.75],...
          'FontSize',12,...
          'FontWeight','b',...
          'String','Rezistenta R:');

Rb=uicontrol('Style','Edit',...
    'Units','Normalized',...
    'Position',[0.09,0.83,0.05,0.03],...
    'FontSize',12,...
    'String',R,...
    'Tag','rezistenta',...
    'Callback','calcul_plot');

uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.15,0.83,0.035,0.03],...
    'BackgroundColor',[0.75,0.75,0.75],...
    'FontSize',12,...
    'String','[ohm]');
%-------------------------------------
uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.085,0.78,0.1,0.03],...
    'BackgroundColor',[0.75,0.75,0.75],...
    'FontSize',12,...
    'FontWeight','b',...
    'String','Inductanta L:');

uicontrol('Style','Edit',...
    'Units','Normalized',...
    'Position',[0.09,0.73,0.05,0.03],...
    'FontSize',12,...
    'String',L,...
    'Tag','inductanta',...
    'Callback','calcul_plot');

uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.15,0.73,0.03,0.03],...
    'BackgroundColor',[0.75,0.75,0.75],...
    'FontSize',12,...
    'String','[H]');
%-------------------------------------
uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.085,0.68,0.1,0.03],...
    'BackgroundColor',[0.75,0.75,0.75],...
    'FontSize',12,...
    'FontWeight','b',...
    'String','Capacitatea C:');

uicontrol('Style','Edit',...
    'Units','Normalized',...
    'Position',[0.09,0.63,0.05,0.03],...
    'FontSize',12,...
    'String',C,...
    'Tag','capacitate',...
    'Callback','calcul_plot');

uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.15,0.63,0.03,0.03],...
    'BackgroundColor',[0.75,0.75,0.75],...
    'FontSize',12,...
    'String','[F]');
 %---------------------------------------------
 uicontrol('Style','PopupMenu',...
           'Units','normalized',...
           'Position',[0.1 0.4 0.12 0.2],...
           'value',tip,...
           'String','FTJ_LR_C|FTS_RC_L|FTB_LC_R|FOB_R_LC|FTJ_L_CR|FTS_C_RL|FTS_C_RL_p|FTB_R_CL_p|FTJ_L_CR_p',...
           'FontSize',15,...
           'ForegroundColor','b',...
           'Tag','pop_menu',...
           'Callback','calcul_plot');
%----------------------------------


%Calcule -> ecuatii
Q=sqrt(L/C)./R;
f0=1/(2*pi*sqrt(L*C));
fmin=f0*(sqrt(1+4*Q.^2)-1)/(2*Q);%frecventa minima a benzii de trecere a circuitului rezonant
fmax=f0*(sqrt(1+4*Q.^2)+1)/(2*Q);
Bf=fmax-fmin;%latimea benzii de trecere
%----------------------------------
uibuttongroup('Visible','on',...
              'BackgroundColor','w',...
              'ForegroundColor','black',...
              'FontSize',15,...
              'TitlePosition','centertop',...
              'Title','Calcule',...
              'Position',[0.065 0.25 0.20 0.25]);
%-------------------------------------------------------
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.08,0.43,0.12,0.03],...
          'BackgroundColor','w',...
          'FontSize',15,...
          'FontWeight','b',...
          'Tag','factor_calitate',...
          'String',['Q = ',num2str(Q)]); 
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.08,0.40,0.12,0.03],...
          'BackgroundColor','w',...
          'FontSize',15,...
          'FontWeight','b',...
          'Tag','frecventa_taiere',...
          'String',[' f0 = ',num2str(fix(f0)),' Hz ']); 
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.09,0.37,0.12,0.03],...
          'BackgroundColor','w',...
          'FontSize',15,...
          'FontWeight','b',...
          'Tag','fmin',...
          'String',['fmin = ',num2str(fix(fmin)),' Hz ']); 
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.085,0.34,0.12,0.03],...
          'BackgroundColor','w',...
          'FontSize',15,...
          'FontWeight','b',...
          'Tag','fmax',...
          'String',['fmax = ',num2str(fix(fmax)),' Hz ']); 
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.09,0.31,0.12,0.03],...
          'BackgroundColor','w',...
          'FontSize',15,...
          'FontWeight','b',...
          'Tag','banda_frecv',...
          'String',['Bf = ',num2str(fix(Bf)),' Hz ']); 

%popup menu pentru selectarea ferestrei cu semnalele vi, vo
uicontrol('Style','PopupMenu',...
           'Units','normalized',...
           'Position',[0.1 0.04 0.1 0.05],...
           'value',alegere,...
           'String','Arata CSTV| NU ARATA CSTV',...
           'FontSize',5,...
           'ForegroundColor','b',...
           'Tag','pop_menu_cstv',...
           'Callback','calcul_plot');
%-------------------------------------------------------------------------

%seria de valori
uicontrol('Style','Text',...
    'Units','Normalized',...
    'Position',[0.03,0.17,0.05,0.05],...
    'BackgroundColor','w',...
    'FontSize',10,...
    'FontWeight','b',...
    'String','Serii:');
 uicontrol('Style','PopupMenu',...
           'Units','normalized',...
           'Position',[0.03 0.12 0.05 0.05],...
           'value',tipr,...
           'String','E6|E12|E24|E48|E96|E192',...
           'FontSize',10,...
           'ForegroundColor','b',...
           'Tag','pop_menu_sr',...
           'Callback','calcul_plot');

 if tipr == 1
     uicontrol('Style','PopupMenu',...
           'Units','normalized',...
           'Position',[0.03 0.07 0.05 0.05],...
           'value',valr,...
           'String','10|15|22|33|47|68',...
           'FontSize',10,...
           'ForegroundColor','b',...
           'Tag','pop_up_menur',...
           'Callback','calcul_plot');
              if valr == 1
               R = 10;
                % set(Rb, 'String', num2str(R)); % Set the 'String' property to the new value
                  set(findobj('Tag', 'rezistenta'), 'String', num2str(R));
              end
               if valr == 2
               R = 15;
                % set(Rb, 'String', num2str(R)); % Set the 'String' property to the new value
                set(findobj('Tag', 'rezistenta'), 'String', num2str(R));
               end
                if valr == 3
               R = 22;
                % set(Rb, 'String', num2str(R)); % Set the 'String' property to the new value
                set(findobj('Tag', 'rezistenta'), 'String', num2str(R));
              end
               if valr == 4
               R = 33;
                % set(Rb, 'String', num2str(R)); % Set the 'String' property to the new value
                set(findobj('Tag', 'rezistenta'), 'String', num2str(R));
               end
                if valr == 5
               R = 47;
                % set(Rb, 'String', num2str(R)); % Set the 'String' property to the new value
                set(findobj('Tag', 'rezistenta'), 'String', num2str(R));
              end
               if valr == 6
               R = 68;
                % set(Rb, 'String', num2str(R)); % Set the 'String' property to the new value
                set(findobj('Tag', 'rezistenta'), 'String', num2str(R));
              end
end
if tipr == 2
     uicontrol('Style','PopupMenu',...
           'Units','normalized',...
           'Position',[0.03 0.07 0.05 0.05],...
           'value',valr,...
           'String','10|12|15|18|22|27|33|39|47|56|68|82',...
           'FontSize',10,...
           'ForegroundColor','b',...
           'Tag','pop_menu_r',...
           'Callback','calcul_plot');
        
end
if tipr == 3
     uicontrol('Style','PopupMenu',...
           'Units','normalized',...
           'Position',[0.03 0.07 0.05 0.05],...
           'value',valr,...
           'String','10|11|12|13|15|16|18|20|22|24|27|27|30|33|36|39|43|47|51|56|62|68|75|82|91',...
           'FontSize',10,...
           'ForegroundColor','b',...
           'Tag','pop_menu_r',...
           'Callback','calcul_plot');
end
if tipr == 4
     uicontrol('Style','PopupMenu',...
           'Units','normalized',...
           'Position',[0.03 0.07 0.05 0.05],...
           'value',valr,...
           'String','100|105|110|115|121|127|133|140|147|154|162|169|178|187|196|205|215|226|237|249|261|274|287|301|316|332|348|365|383|402|422|442|464|487|511|536|562|590|619|649|681|715|750|787|825|866|909|953',...
           'FontSize',10,...
           'ForegroundColor','b',...
           'Tag','pop_menu_r',...
           'Callback','calcul_plot');
end
if tipr == 5
     uicontrol('Style','PopupMenu',...
           'Units','normalized',...
           'Position',[0.03 0.07 0.05 0.05],...
           'value',valr,...
           'String','10|15|22|33|47|68',...
           'FontSize',10,...
           'ForegroundColor','b');
           % 'Tag','pop_menu_sr',...
           % 'Callback','calcul_plot');
end
if tipr == 6
     uicontrol('Style','PopupMenu',...
           'Units','normalized',...
           'Position',[0.03 0.07 0.03 0.05],...
           'value',valr,...
           'String','10|15|22|33|47|68',...
           'FontSize',10,...
           'ForegroundColor','b');
           % 'Tag','pop_menu_sr',...
           % 'Callback','calcul_plot');
end


 % uicontrol('Style','PopupMenu',...
 %           'Units','normalized',...
 %           'Position',[0.09,0.83,0.05,0.03],...
 %           'value',tipr,...
 %           'String','100|105|110|115|121|127|133|140|147|154|162|169|178|187|196|205|215|226|237|249|261|274|287|301|316|332|348|365|383|402|422|442|464|487|511|536|562|590|619|649|681|715|750|787|825|866|909|953',...
 %           'FontSize',10,...
 %           'ForegroundColor','b',...
 %           'Tag','rezistenta',...
 %           'Callback','calcul_plot');
 % uicontrol('Style','PopupMenu',...
 %           'Units','normalized',...
 %           'Position',[0.09,0.63,0.05,0.03],...
 %           'value',tipc,...
 %           'String','1e-6|10e-6|15e-6|20e-6|30e-6|33e-6|47e-6|56e-6|68e-6|75e-6|82e-6|91e-6|100e-6|120e-6|130e-6|150e-6|180e-6|220e-6|330e-6|470e-6|560e-6|680e-6|750e-6|820e-6|1000e-6|1500e-6',...
 %           'FontSize',10,...
 %           'ForegroundColor','b',...
 %           'Tag','capacitate',...
 %           'Callback','calcul_plot');

meniu=uimenu('Label','Documentatie');%Interfata
submeniu1_1=uimenu(meniu,'Label','Descriere','Callback','filtre');


